author: Tobe O <thosakwe@gmail.com>
description: Manga Eden client PWA.
homepage: https://github.com/thosakwe/manga-zap2.git
name: manga_zap
publish_to: none
version: 1.0.0
dependencies: 
  angular: ^5.0.0-alpha
  angular_components: ^0.9.0-alpha
  angular_forms: ^2.0.0-alpha
  angular_router: ^2.0.0-alpha
  html_unescape: ^0.1.4
  pwa: ^0.1.10
dev_dependencies:
  build_runner: ^0.8.0
  build_web_compilers: ^0.4.0
  sass_builder: ^2.0.0